name: Selenium Headless Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Set environment variable for headless execution
      - name: Set execution environment
        run: echo "execution_env=remote" >> $GITHUB_ENV

      # Step 4: Build and run Maven tests
      - name: Run Maven tests
        run: mvn clean test

      # Step 5: Upload screenshots as artifacts (optional)
      - name: Upload screenshots
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
