name: Maven CI

on:
  push:        # Run workflow on every push
    branches: [ "master" ]
  pull_request: # Run on pull requests
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Cache Maven dependencies (faster builds)
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Step 4: Build project
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 5: Run Tests
    - name: Run tests
      run: mvn test
